### ISSUE TITLE
Make WAMP point to WP-Repository

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#4]
Currently [WAMP ](http://www.wampserver.com/en/) hosts code in the C:/wamp/www folder on a local machine. Investigate if it is possible to point to code in a repo on a different path (i.e. C:\C) OPEN DOOR BREW CO\5) TECHNOLOGY\Website\odbc-wp). This way only one copy of code is kept and it is in a sensible location on the local machine.

**Comment by michaelbadaracca** [comment]
Was able to create an Alias in WAMP to point to the desired directory. The alias **localhost/odbc-wp** points to the location of my local git repo for odbc-wp.

The following forum was very informative for creating aliases and also had interesting information about creating new virtual hosts which may be worth looking into at some point: http://forum.wampserver.com/read.php?2,89163,89187 

### Creating a new alias
- Open an explorer window and navigate to c:/wamp/alias
- Copy phpmyadmin.conf and rename it
- Edit the file
  - replace the alias with the desired alias (i.e. odbc-wp)
  - replace alias path with path of desired local directory
  - replace the value of the **Directory** tag with the path of the desired local directory
- Save the file
- Restart WAMP services
  - left click WAMP icon in system tray
  - click **Restart All Services**
- open a browser and navigate to **localhost/yourAlias** to test if the alias is working

**Comment by michaelbadaracca** [comment]
Issue accessing wp-admin section. When I navigate to localhost/odbc-wp/wp-admin it seems to redirect to a different wp-admin (like the one in c:/wamp/www)

Redirect from localhost/odbc-wp/wp-admin:

http://localhost/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%2Fodbc-wp%2Fwp-admin%2F&reauth=1

Redirect from localhost/wp-admin:

http://localhost/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%2Fwp-admin%2F&reauth=1

**Comment by michaelbadaracca** [comment]
I am going to try creating a new virtual host. I think what is happening is that localhost has a DB for WP content. This contains the appropriate login credentials which need the correct username and password, but also the wp-admin location needs to be the same as what is stored in the DB. Creating a new virtual host may clean things up a bit. This will probably involve re-creating WP-content.

**Comment by michaelbadaracca** [comment]
Was able to login by going to localhost/odbc-wp/wp-login and entering credentials. It redirects to localhost though, not localhost/odbc-wp.

There is some useful information in this post: http://stackoverflow.com/questions/15557718/after-migration-of-wordpress-website-i-cant-access-the-admin-white-page

**Comment by michaelbadaracca** [comment]
Created Virtual host in issue #5 (**odbc.localhost** ) and created new db (**odbc_wp_3**) in issue #6. The virtual host points to a local git repo and the new db (with copied content) makes all pages resolve to odbc.localhost instead of localhost.
