### ISSUE TITLE
Create new Virtual Host for local development

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#5]
Create a virtual host for local development that points to the desired folder with wp-code under source control. 

Use this as a resource: http://forum.wampserver.com/read.php?2,89163,89187

**Comment by michaelbadaracca** [comment]
Followed instructions from http://forum.wampserver.com/read.php?2,89163,89187. Ran into an 403 error (You don't have permission to access / on this server) I followed the directions from this blog http://stackoverflow.com/questions/10859271/wampserver-403-on-named-virtual-hosts-outside-of-www and commented out a directory tag.

**Comment by michaelbadaracca** [comment]
Created virtual host called odbc.localhost
