### ISSUE TITLE
Create a new local wp-installation on new Virtual host

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#6]
Create a new local  DB on WAMP for new WP install. Make sure to setup pretty permalinks from the beginning. Realted to issue #5 .

**Comment by michaelbadaracca** [comment]
- Created new DB in phpMyAdmin called odbc_wp_3.
- Started from scratch with a new installation of WordPress (Version 4.0.1).
- Set permalinks to **Post Name**

Followed instructions from this forum:
http://www.wpbeginner.com/wp-tutorials/how-to-install-wordpress-on-your-windows-computer-using-wamp/

**Comment by michaelbadaracca** [comment]
Ran into issue with permalinks now being recognized for post name. This was solved by enabling the rewrite module on the WAMP Apache Server. 

The following forum was helphul: https://wordpress.org/support/topic/the-requested-url-xxxx-was-not-found-on-this-server

Specifically this comment:

> If you want to use permalinks, you will need to make a change inside another file:
> Click the Start button, followed by My Computer > Main drive > Xampplite > apache > Conf and find the file httpd.conf. Open that in a text editor. Use the search facility in the editor to find "rewrite". The line you need looks like this:
> 
> #LoadModule rewrite_module modules/mod_rewrite.so
> 
> You need to take away the hash sign so it looks like this
> 
> LoadModule rewrite_module modules/mod_rewrite.so
> 
> Now just save the file.

**Comment by michaelbadaracca** [comment]
Re-created following pages from previous WP installation:
- About
- Contact
- Blog
- Age check

NOTE: these pages are referencing images on the localhost DB, not the odbc.localhost DB (odbc_wp_3)

**Comment by michaelbadaracca** [comment]
Re-created dummy blog posts. Added the **post-image-small** custom field from each post

**Comment by michaelbadaracca** [comment]
Added ODBC theme. Need to update page templates. Need to update navigation to get WP style navigation and supress it from the header.

**Comment by michaelbadaracca** [comment]
Created a menu called **Main Nav Menu** with the following items:
- About
- Blog

Added the **moveUp top-nav** css class to each menu item

I believe this menu name is hardcoded somewhere.

**Comment by michaelbadaracca** [comment]
Updated page templates for Blog and Age Check

**Comment by michaelbadaracca** [comment]
Updated home link in header to grab the location of the homepage rather than use a static link.
