### ISSUE TITLE
Integrate JCreativ Theme with WordPress installation

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#8]

**Comment by michaelbadaracca** [comment]
Encountered this Error:
Fatal error: Call to undefined function vp_metabox() in C:\C) OPEN DOOR BREW CO\5) TECHNOLOGY\Website\odbc-wp\wp-content\themes\jkreativ-themes\lib\scriptstyle.php on line 497

![image](https://cloud.githubusercontent.com/assets/8838050/5511374/fddf9734-8789-11e4-89e9-cb0851354068.png)

**Comment by michaelbadaracca** [comment]
Activating the JKreativ Plugin fixed the error above

**Comment by michaelbadaracca** [comment]
Look into activating Envato ToolKit
http://www.wpexplorer.com/envato-wordpress-toolkit-guide/

**Comment by michaelbadaracca** [comment]
Created rough landing page with JKreativ theme. Reference Issue #11
