### ISSUE TITLE
Purchase and install Visual Composer

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#9]

**Comment by michaelbadaracca** [comment]
Purchased Visual Composer and entered the license code as well as the Envato Toolkit credentials (http://www.wpexplorer.com/envato-wordpress-toolkit-guide/).

**Comment by michaelbadaracca** [comment]
Visual composer seems to working incorrectly with the JKreativ theme and/or associated plugins. When all plugins (other that Visual Composer) are turned off and the theme is switched to 2015, Visual composer seems to work as intended, showing both the front-end and back-end editing options.
![image](https://cloud.githubusercontent.com/assets/8838050/5761827/43dbc318-9c9b-11e4-857c-5fce5996548b.png)

When JKreativ theme is activated and only the Visual COmposer Plugin is active, it seems to function properly. When all plugins are active with the JKreativ theme, Visual Composer does not show the front-end editor. Activating only the Visual Composer and JKreativ plugins, the front-end editor is not working.

![image](https://cloud.githubusercontent.com/assets/8838050/5762113/11b8d18a-9c9d-11e4-9da1-1822da1b2c8f.png)

**Comment by michaelbadaracca** [comment]
Got Visual Composer working with the latest version of WordPress (version 4.1 at the time of this comment). I increased the memory allocated on the server (localhost) from 48 mb to 96 mb and Visual Composer seemed to work better.
